INSERT INTO Categorias VALUES(1,"Bebidas","Gaseosas, café, té, cervezas y maltas");
INSERT INTO Categorias VALUES(2,"Condimentos","Salsas dulces y picantes, delicias, comida para untar y aderezos");
INSERT INTO Categorias VALUES(3,"Repostería","Postres, dulces y pan dulce");
INSERT INTO Categorias VALUES(4,"Lácteos","Quesos");
INSERT INTO Categorias VALUES(5,"Granos/Cereales","Pan, galletas, pasta y cereales");
INSERT INTO Categorias VALUES(6,"Carnes","Carnes preparadas");
INSERT INTO Categorias VALUES(7,"Frutas/Verduras","Frutas secas y queso de soya");
INSERT INTO Categorias VALUES(8,"Pescado/Marisco","Pescados, mariscos y algas");
INSERT INTO Productos VALUES(1,1,"Té Dharamsala","10 cajas x 20 bolsas",4);
INSERT INTO Productos VALUES(2,1,"Cerveza tibetana","24 - bot. 12 fl.",23);
INSERT INTO Productos VALUES(3,2,"Sirope de regaliz","12 - bot. 550 ml",12);
INSERT INTO Productos VALUES(4,2,"Especias Cajun del chef Anton","48 - frascos de 6",23);
INSERT INTO Productos VALUES(5,2,"Mezcla Gumbo del chef Anton","Condimentos 36 cajas",34);
INSERT INTO Productos VALUES(6,2,"Mermelada grosellas abuela","12 - frascos de 8",45);
INSERT INTO Productos VALUES(7,7,"Peras orgánicas tío Bob","12 - paq. 1 kg",23);
INSERT INTO Productos VALUES(8,3,"Cuajada de judías","40 - paq. 100 g",60);
INSERT INTO Productos VALUES(9,6,"Buey Mishí Kobe","18 - paq. 500 g",55);
INSERT INTO Productos VALUES(10,8,"Pez espada","12 - frascos 200 ml",56);
INSERT INTO Productos VALUES(11,3,"Cordero Alice Springs","20 - latas 1 kg",60);
INSERT INTO Productos VALUES(12,4,"Queso Cabrales","1 kg",12);
INSERT INTO Productos VALUES(13,4,"Queso Manchego La Pastora","10 - paq. 500 g",10);
INSERT INTO Productos VALUES(14,8,"Algas Konbu Mayumi's","caja 2 kg",45);
INSERT INTO Productos VALUES(15,8,"Langostinos tigre Carnarvon","paq. 16 kg",35);
INSERT INTO Productos VALUES(16,3,"Postre de merengue Pavlova","g",25);
INSERT INTO Productos VALUES(17,3,"Pastas de té chocolate","10 cajas x 12 piezas",45);
INSERT INTO Productos VALUES(18,8,"Langostinos tigre Carnarvon","32 - cajas 500 g",20);
INSERT INTO Productos VALUES(19,3,"Pastas de té chocolate","10 cajas x 12 piezas",45);
INSERT INTO Productos VALUES(20,3,"Mermelada Sir Rodney's regalo","30 cajas",15);
